<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>false</SelfContained>
    <PublishReadyToRun>false</PublishReadyToRun>
    <Version>1.2.0</Version>
    <Product>MasterAuthenticator</Product>
    <Description>Master Authenticator - מנהל סיסמאות ו-TOTP</Description>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Resources\*.png" />
    <Resource Include="app.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Drawing.Common" Version="10.0.9" />
    <PackageReference Include="ZXing.Net" Version="0.16.9" />
  </ItemGroup>

</Project>
